### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [gutmann03/arithmetic_parser_kma#1]
Student: Сметанюк Володимир

Не вистачає для прохідного:
✔️ ! Project Name: 
✔️ ! Grammar Rules: я зарахую, але поки не гарантую, що інші погодяться
✔️ ! CLI: немає
✔️ ! Brief Description:
✔️ ! Unit Tests:
✔️ ! Core Files:

Не вистачає для мааксимального:
❌ File System: потрібне не тільки зчитування з файлу, а й запис у нього.
✔️ Test Coverage: проте
❌ Error Handling: краще заміни unrechable!() на помилку
✔️ cargo fmt:
❌ cargo clippy:
✔️ makefile:
❌ Completeness: спершу інші пункти
✔️ Including a diagram or grammar in the Readme.md:
✔️Documentation:
✔️ Publishing: оновиш без фамілії

✔️ Курсова може бути зарахована
Бал: 15 з 25

**Comment by NYBACHOK** [comment]
Привіт. Оновив. Напииши якщо погоджуєшся з балом

**Comment by gutmann03** [comment]
Вітаю! Так, погоджуюсь.
